### ISSUE TITLE
Doesn't work on Kitkat / FP1

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/flashable-zip_noto-emoji#1] opened 2018-06-26 16:12 UTC
Flashing this via `adb sideload` results in an empty emoji drawer (there seem to be "things" that are clickable and are inserted in messages, but everything is blank).

![img_20180626_181023](https://user-images.githubusercontent.com/8948865/41925353-a7b5dfac-796c-11e8-991d-7b4deab8d75a.JPG)

Edit: The font in [this zip on mega.nz](https://mega.nz/#!rkpGFQxA!F4HY-XDY8brbCfRHtxZKkiYvf9k_uk0Xi1t4Pqzj_6I) works fine (though I don't get _more_ emojis, they just look differently).

**Comment by Roboe** [comment] 2018-06-30 13:14
Hmmm, it seems like the format of the font is not compatible with KitKat. I get the NotoColorEmoji right from the official repo: https://github.com/googlei18n/noto-emoji/tree/master/fonts

It may be that I've made something wrong with this new build system for the flashable ZIPs that breaks things in older versions. I think you used [my EmojiOne](https://github.com/WeAreFairphone/flashable-zip_emojione) in the past, right? Since the EmojiOne v2 font worked and has not been updated in a while, could you test if this new re-packaged ZIP works fine? [emojione-v2.2.7_2018-06-30.zip](https://github.com/WeAreFairphone/flashable-zip_noto-emoji/files/2151724/emojione-v2.2.7_2018-06-30.zip)

>  The font in this zip on mega.nz works fine

Source? I can't cherypick fonts from unknown sources and without version info, :/
(that's the reason I've not made yet a Twemoji flashable ZIP)

**Edit:** I've checked and it isn't one of the official binaries, so it may be modified somehow:
```
$ sha1sum *.ttf
6c1f30c532ea246c85c16d03bf178dd67e6fbd07  NotoColorEmoji-mega-unkwnown.ttf
e3c9d6420ed295523a58b35bd1b53a0efbdd5b93  NotoColorEmoji_v2017-03-10-color-emoji-binary.ttf
cff1cfa9f1909587f1e0121081008ef4ac38b4a1  NotoColorEmoji_v2017-04-03-update-for-noto-site.ttf
0db2a46fc2e4784b271c6bd416fe6f23acf3abd6  NotoColorEmoji_v2017-05-18-cook-color-fix.ttf
3d894afdfa703f231db4db3d25450c2691eaa6f9  NotoColorEmoji_v2017-09-13-design-refresh.ttf
c2d6317ec050d53a6ae35d0f620311bcd378c315  NotoColorEmoji_v2017-12-04-hamburger-fix.ttf
fd1d07f7523ac4bd4ecff2b889a411c267b23ee2  NotoColorEmoji_v2018-01-02-flag-update.ttf
c3985826eb3fe2c139cf1ef6964ab0f3dcf9f141  NotoColorEmoji_v2018-04-24-pistol-update.ttf
```

> (though I don't get more emojis, they just look differently)

Fonts can't add emojis to the keyboard because it has a harcoded list of emojis. But when you found [new ones](https://emojipedia.org/unicode-10.0/) in the wild, they should render fine. Like 🧐, 🤯, 🤪 or 🧘

**Comment by StefanBrand** [comment] 2018-07-15 10:41
> Since the EmojiOne v2 font worked and has not been updated in a while, could you test if this new re-packaged ZIP works fine? emojione-v2.2.7_2018-06-30.zip

Yep, this one works fine. :) It's kinda outdated though. ☺️ looks very similar to 🙂 , when it should be more like 😊 to be consistent with other implementations.

**Comment by Roboe** [comment] 2018-07-18 20:37
Thanks!

Yeah, I know the caveats of EmojiOne, thus this repo, ;)

This shows that the NotoEmoji font provided by upstream is not compatible with Android 4.4 for some unknown reason —by asserting I've not introduced any regression with the new build system, which makes me feel good.

So, first, **a note about compatibility should be mentioned somewhere** (mental note).

Finally, I could make an exceptional release (in another branch) with the font you provided, clearly stating that I won't be able to update it future-wise, 🤷‍♂️ (unless I find/someone points a method to convert upstream fonts to a compatible format, which is unlikely)

**Comment by StefanBrand** [comment] 2018-08-07 17:46
I think that the demand is not too high. ;) (Especially since the keyboard cannot make use of the newer emojis...)

**Comment by Roboe** [comment] 2018-08-16 23:42
Would you like me to make the exceptional release? If that helps you, I'll happily do it. It won't be much work for me, don't worry.

**Comment by StefanBrand** [comment] 2018-08-17 08:33
Not necessary for me. :)
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 17. August 2018 01:42:16 MESZ schrieb Roberto MF <notifications@github.com>:
>Would you like me to release the exceptional release? If that helps
>you, I'll happily do it. It won't be much work.

**Comment by Roboe** [comment] 2018-08-18 16:22
Fine, :)

I've decided not to block the installation on pre-Lollipop devices in the code, but I've put a compatibility note in the releases page.

Closing this now, thank you! :+1:

**Closed as completed by Roboe** 2018-08-18 16:22 UTC
